image: cr.yandex/crp742p3qacifd2hcon2/practice-da:latest

stages:
    - init
    - run

report_job_1:
    stage: run
    only:
        - schedules
    script:
        - python report_telegram_group.py

report_job_2:
    stage: run 
    only: 
        - schedules
    script: 
        - python full_report.py
